program: train_model.py
method: bayes # Choose between 'grid', 'random', or 'bayes'
metric:
  name: loss
  goal: minimize
parameters:
  lr:
    distribution: uniform
    min: 0.0001
    max: 0.1
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
# command:
#   - ${env:PYTHONPATH}
#   - ${env:PYTHONUNBUFFERED}
#   - ${env:WANDB_RUN_ID}
#   - ${env:WANDB_API_KEY}
