program: train_model.py
method: bayes # grid, random, bayes
metric:
  name: loss
  goal: minimize
parameters:
  lr:
    distribution: uniform
    min: 0.0001
    max: 0.1
  batch_size:
    values: [32, 64, 128]
  epochs:
    values: [10, 20, 30]
