FROM python:3.11-slim

# install python
RUN apt update && \
    apt install --no-install-recommends -y build-essential gcc && \
    apt clean && rm -rf /var/lib/apt/lists/*

COPY mlops_repo/requirements.txt mlops_repo/requirements.txt
COPY main.py main.py
WORKDIR /
RUN pip install -r mlops_repo/requirements.txt --no-cache-dir

ENTRYPOINT ["python", "-u", "main.py"]