wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.15
    cli_version: 0.16.6
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717335398.0
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 103
      - 105
      2:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 103
      - 105
      3:
      - 7
      - 23
      4: 3.9.15
      5: 0.16.6
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
